"""Protocol a player backend implements to register at the ``player.backends`` extension point.

Optional capabilities (library browsing, cover art, rewind, ...) are looked up by name at call
time; a backend without them makes the corresponding operation answer 501.
"""

from typing import Any, Callable, Dict, List, Mapping, Protocol


class PlayerBackend(Protocol):
    def set_status_callback(self, callback: Callable[[Mapping[str, Any]], None]) -> None:
        """Receive the raw status mapping whenever it changes (only forwarded while active)."""

    def set_active(self, active: bool) -> None: ...

    def play(self) -> None: ...

    def stop(self) -> None: ...

    def pause(self, state: int = 1) -> None: ...

    def prev(self) -> None: ...

    def next(self) -> None: ...

    def seek(self, new_time: float) -> None: ...

    def toggle(self) -> None: ...

    def shuffle(self, option: str = 'toggle') -> None: ...

    def repeat(self, option: str = 'toggle') -> None: ...

    def play_single(self, song_url: str) -> None: ...

    def play_folder(self, folder: str, recursive: bool = False) -> None: ...

    def play_files(self, paths: List[str]) -> None:
        """Replace the queue with ``paths`` (absolute or relative to the music library) and play."""

    def is_second_swipe(self, folder: str) -> bool: ...

    def play_second_swipe(self) -> None: ...

    def playerstatus(self) -> Mapping[str, Any]: ...

    def playlistinfo(self) -> List[Dict[str, Any]]: ...

    def get_volume(self) -> int: ...

    def set_volume(self, volume: int) -> int: ...

    def exit(self) -> Any: ...
