services:
  mpd:
    build:
      args:
        - UID=0
        - USER=root
        - HOME=/root
      context: ../
      dockerfile: ./docker/Dockerfile.mpd
    container_name: mpd
    image: lauschkiste/mpd
    environment:
      - PULSE_SERVER=tcp:host.docker.internal:4713
    restart: unless-stopped
    volumes:
      - ../shared/audiofolders:/root/lauschkiste/shared/audiofolders
      - ../shared/playlists:/root/.config/mpd/playlists
      - ./config/docker.mpd.conf:/root/.config/mpd/mpd.conf

  lauschkiste:
    build:
      args:
        - UID=0
        - USER=root
        - HOME=/root
      context: ../
      dockerfile: ./docker/Dockerfile.lauschkiste
    container_name: lauschkiste
    image: lauschkiste/server
    depends_on:
      - mpd
    environment:
      - PULSE_SERVER=tcp:host.docker.internal:4713
    ports:
      - 5556:5556
    restart: unless-stopped
    tty: true
    volumes:
      - ../packages/lauschkiste:/root/lauschkiste/packages/lauschkiste
      - ../packages/cli:/root/lauschkiste/packages/cli
      - ../packages/webapp/public/cover-cache:/root/lauschkiste/packages/webapp/build/cover-cache
      - ../shared:/root/lauschkiste/shared
      - ./config/docker.mpd.conf:/root/.config/mpd/mpd.conf
    command: lauschkiste

  webapp:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.webapp
    container_name: webapp
    image: lauschkiste/webapp
    depends_on:
      - lauschkiste
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_PROXY_TARGET=http://lauschkiste:5556
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ../packages/webapp:/home/node/webapp
      - /home/node/webapp/node_modules
