services:
  mpd:
    build:
      args:
        - UID=${UID:-1000}
        - USER=pi
        - HOME=/home/pi
    environment:
      - PULSE_SERVER=unix:/tmp/pulse-sock
    volumes:
      - ../shared/library:/home/pi/lauschkiste/shared/library
      - ../shared/playlists:/home/pi/.config/mpd/playlists
      - ./config/docker.mpd.conf:/home/pi/.config/mpd/mpd.conf
      - $XDG_RUNTIME_DIR/pulse/native:/tmp/pulse-sock

  lauschkiste:
    build:
      args:
        - UID=${UID:-1000}
        - USER=pi
        - HOME=/home/pi
    environment:
      - PULSE_SERVER=unix:/tmp/pulse-sock
    volumes:
      - ../shared:/home/pi/lauschkiste/shared
      - ./config/docker.mpd.conf:/home/pi/.config/mpd/mpd.conf
      - $XDG_RUNTIME_DIR/pulse/native:/tmp/pulse-sock
